### ISSUE TITLE
Broken link in Docker Install instructions

### ISSUE THREAD

**Issue by TimStewartJ** [Kareadita/Wiki#26]
The very last line in the [Docker Install](https://github.com/Kareadita/Wiki/blob/main/pages/02.install/02.docker-install/default.md) instructions links to `../../03.guides/01.first-time-setup/default.en.md` which doesn't exist any more. Should it be `../../03.guides/01.first-time-setup/docs.en.md` instead? Not sure, just caught me off guard when I tried following along.

**Comment by therobbiedavis** [comment]
@TimStewartJ Thank you for opening this issue. This has now been fixed with e844c8d
